/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package multi_gato;

import javax.swing.*;
import java.awt.*;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author diazt
 */
public class GatoPrincipal extends javax.swing.JFrame {
    JLabel actualTurn=new JLabel();
    JLabel timeLeft=new JLabel();
    String turn="X";
    JLabel boxes[]=new JLabel[9];
    Timer timer = new Timer();
    int champions[][]={
        {1,2,3},
        {4,5,6},
        {7,8,9},
        {1,4,7},
        {2,5,8},
        {3,6,9},
        {1,5,9},
        {3,5,7}
    };
    
    
    
    public GatoPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        boxes[0]=BoxSI;
        boxes[1]=BoxSC;
        boxes[2]=BoxSD;
        
        boxes[3]=BoxCI;
        boxes[4]=BoxCC;
        boxes[5]=BoxCD;
        
        boxes[6]=BoxII;
        boxes[7]=BoxIC;
        boxes[8]=BoxID;
        
        actualTurn=Turno;
        timeLeft=Tiempo;
        
        

    }
    
    //Color fondito=boxes[0].getBackground();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BoxSI = new javax.swing.JLabel();
        BoxSC = new javax.swing.JLabel();
        BoxSD = new javax.swing.JLabel();
        BoxCI = new javax.swing.JLabel();
        BoxCC = new javax.swing.JLabel();
        BoxCD = new javax.swing.JLabel();
        BoxII = new javax.swing.JLabel();
        BoxIC = new javax.swing.JLabel();
        BoxID = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Turno = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GatoPrincipal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(23, 190, 187));

        BoxSI.setBackground(new java.awt.Color(0, 0, 0));
        BoxSI.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxSI.setForeground(new java.awt.Color(239, 122, 26));
        BoxSI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxSI.setOpaque(true);
        BoxSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxSIMousePressed(evt);
            }
        });

        BoxSC.setBackground(new java.awt.Color(0, 0, 0));
        BoxSC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxSC.setForeground(new java.awt.Color(239, 122, 26));
        BoxSC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxSC.setOpaque(true);
        BoxSC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxSCMousePressed(evt);
            }
        });

        BoxSD.setBackground(new java.awt.Color(0, 0, 0));
        BoxSD.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxSD.setForeground(new java.awt.Color(239, 122, 26));
        BoxSD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxSD.setOpaque(true);
        BoxSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxSDMousePressed(evt);
            }
        });

        BoxCI.setBackground(new java.awt.Color(0, 0, 0));
        BoxCI.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxCI.setForeground(new java.awt.Color(255, 203, 71));
        BoxCI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxCI.setOpaque(true);
        BoxCI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxCIMousePressed(evt);
            }
        });

        BoxCC.setBackground(new java.awt.Color(0, 0, 0));
        BoxCC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxCC.setForeground(new java.awt.Color(239, 122, 26));
        BoxCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxCC.setOpaque(true);
        BoxCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxCCMousePressed(evt);
            }
        });

        BoxCD.setBackground(new java.awt.Color(0, 0, 0));
        BoxCD.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxCD.setForeground(new java.awt.Color(239, 122, 26));
        BoxCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxCD.setOpaque(true);
        BoxCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxCDMousePressed(evt);
            }
        });

        BoxII.setBackground(new java.awt.Color(0, 0, 0));
        BoxII.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxII.setForeground(new java.awt.Color(239, 122, 26));
        BoxII.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxII.setOpaque(true);
        BoxII.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxIIMousePressed(evt);
            }
        });

        BoxIC.setBackground(new java.awt.Color(0, 0, 0));
        BoxIC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxIC.setForeground(new java.awt.Color(255, 203, 71));
        BoxIC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxIC.setOpaque(true);
        BoxIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxICMousePressed(evt);
            }
        });

        BoxID.setBackground(new java.awt.Color(0, 0, 0));
        BoxID.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BoxID.setForeground(new java.awt.Color(255, 203, 71));
        BoxID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BoxID.setOpaque(true);
        BoxID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BoxIDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BoxSI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxSC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxSD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BoxCI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxCC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxCD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BoxII, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxIC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxSI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxSC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxSD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxCI, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxCD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxCC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxII, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxIC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("MULTI GATO");

        Turno.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Turno.setForeground(new java.awt.Color(255, 255, 255));
        Turno.setText("TURNO: O");

        Tiempo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo.setText("TIME: ");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESTART");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("START");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Turno)
                    .addComponent(Tiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxSIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxSIMousePressed
        onPressBox(0);
    }//GEN-LAST:event_BoxSIMousePressed

    private void BoxCIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxCIMousePressed
        onPressBox(3);
    }//GEN-LAST:event_BoxCIMousePressed

    private void BoxCCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxCCMousePressed
        onPressBox(4);
    }//GEN-LAST:event_BoxCCMousePressed

    private void BoxCDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxCDMousePressed
        onPressBox(5);
    }//GEN-LAST:event_BoxCDMousePressed

    private void BoxIIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxIIMousePressed
        onPressBox(6);
    }//GEN-LAST:event_BoxIIMousePressed

    private void BoxICMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxICMousePressed
        onPressBox(7);
    }//GEN-LAST:event_BoxICMousePressed

    private void BoxIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxIDMousePressed
        onPressBox(8);
    }//GEN-LAST:event_BoxIDMousePressed

    private void BoxSDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxSDMousePressed
        onPressBox(2);
    }//GEN-LAST:event_BoxSDMousePressed

    private void BoxSCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxSCMousePressed
        onPressBox(1);
    }//GEN-LAST:event_BoxSCMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        restartGame();
        startClock(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        startClock(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void onPressBox(int casilla){
        if(boxes[casilla].getText().equals("")){
            boxes[casilla].setText(turn);
            if(boxes[casilla].getText().equals("X")){
                boxes[casilla].setForeground(Color.WHITE);
            }else{
                boxes[casilla].setForeground(Color.ORANGE);
            }
            changeTurn();
            showWinner();
        }
    }
    
    public void changeTurn(){
        if(turn.equals("X")){
            turn="O";
        }else{
            turn="X";
        }
        actualTurn.setText("TURNO: "+turn);
    }
    
    public void showWinner(){
        for(int i=0;i<champions.length;i++){
            if(boxes[champions[i][0]-1].getText().equals("X")&& boxes[champions[i][1]-1].getText().equals("X")&&boxes[champions[i][2]-1].getText().equals("X")){
                boxes[champions[i][0]-1].setBackground(Color.lightGray);
                boxes[champions[i][1]-1].setBackground(Color.lightGray);
                boxes[champions[i][2]-1].setBackground(Color.lightGray);
                startClock(false);
                
                /*boxes[0].setText("");
                boxes[1].setText("");
                boxes[2].setText("");
                boxes[3].setText("");
                boxes[4].setText("");
                boxes[5].setText("");
                boxes[6].setText("");
                boxes[7].setText("");
                boxes[8].setText("");*/
                
            }
            if(boxes[champions[i][0]-1].getText().equals("O")&& boxes[champions[i][1]-1].getText().equals("O")&&boxes[champions[i][2]-1].getText().equals("O")){
                boxes[champions[i][0]-1].setBackground(Color.lightGray);
                boxes[champions[i][1]-1].setBackground(Color.lightGray);
                boxes[champions[i][2]-1].setBackground(Color.lightGray);
                startClock(false);
            }
        }
    }
    
    public void restartGame(){
        boxes[0].setText("");
        boxes[1].setText("");
        boxes[2].setText("");
        boxes[3].setText("");
        boxes[4].setText("");
        boxes[5].setText("");
        boxes[6].setText("");
        boxes[7].setText("");
        boxes[8].setText("");
        
        boxes[0].setBackground(Color.black);
        boxes[1].setBackground(Color.black);
        boxes[2].setBackground(Color.black);
        boxes[3].setBackground(Color.black);
        boxes[4].setBackground(Color.black);
        boxes[5].setBackground(Color.black);
        boxes[6].setBackground(Color.black);
        boxes[7].setBackground(Color.black);
        boxes[8].setBackground(Color.black);
        
        
    }
    
    public void startClock(boolean clockState){
        timer.scheduleAtFixedRate(new TimerTask() {
            int i = 60;

            public void run() {

                timeLeft.setText("TIME: " + i);
                i--;

                if (i < 0 || clockState==false) {
                    timer.cancel();
                    timeLeft.setText("TIME OVER");
                }
            }
        }, 0, 1000);
    }
    
            
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoxCC;
    private javax.swing.JLabel BoxCD;
    private javax.swing.JLabel BoxCI;
    private javax.swing.JLabel BoxIC;
    private javax.swing.JLabel BoxID;
    private javax.swing.JLabel BoxII;
    private javax.swing.JLabel BoxSC;
    private javax.swing.JLabel BoxSD;
    private javax.swing.JLabel BoxSI;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Turno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
